#!/usr/bin/env python3
import argparse
import json
import re
import unicodedata
from datetime import date
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate publicaciones item pages from citekeys in _index.md."
    )
    parser.add_argument(
        "--index-file",
        default="content/publicaciones/_index.md",
        help="Path to _index.md containing citekeys.",
    )
    parser.add_argument(
        "--output-dir",
        default="content/publicaciones",
        help="Directory where per-item .md files are created.",
    )
    parser.add_argument(
        "--references",
        default="content/publicaciones/references.json",
        help="Path to references.json.",
    )
    return parser.parse_args()


def yaml_quote(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def ymd_from_obj(obj):
    if not isinstance(obj, dict):
        return ""
    dps = obj.get("date-parts", [])
    if not dps or not dps[0]:
        return ""
    p = dps[0]
    if len(p) == 1:
        return f"{int(p[0]):04d}-01-01"
    if len(p) == 2:
        return f"{int(p[0]):04d}-{int(p[1]):02d}-01"
    return f"{int(p[0]):04d}-{int(p[1]):02d}-{int(p[2]):02d}"


def extract_citekeys(md_text):
    keys = []
    seen = set()

    for m in re.finditer(r"(?<!\w)@([A-Za-z0-9:_\-.]+)", md_text):
        key = m.group(1)
        if key not in seen:
            seen.add(key)
            keys.append(key)

    for m in re.finditer(r'\{\{<\s*cite\s+key="([^"]+)"\s*>\}\}', md_text):
        key = m.group(1).strip()
        if key and key not in seen:
            seen.add(key)
            keys.append(key)

    return keys


def strip_front_matter(md_text: str) -> str:
    m = re.match(r"(?s)\A---\n.*?\n---\n?", md_text)
    if not m:
        return md_text
    return md_text[m.end() :]


def normalize_heading(text: str) -> str:
    text = text.strip().lower()
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = re.sub(r"[^a-z0-9]+", " ", text).strip()
    return text


def heading_to_type(heading: str) -> str:
    h = normalize_heading(heading)
    if h in {"working papers", "working paper", "work in progress", "wip"}:
        return "working_papers"
    if h in {"forthcoming", "en prensa", "in press"}:
        return "en_prensa"
    if h in {"articulos", "articulo", "articles", "article"}:
        return "articulos"
    if h in {"capitulos", "capitulo", "chapters", "chapter", "books", "book"}:
        return "capitulos"
    if h in {"reviews", "review", "resenas", "resena"}:
        return "reviews"
    if h in {"retirados", "withdrawn", "retired"}:
        return "retirados"
    return "articulos"


def extract_citekeys_by_section(md_text: str):
    body = strip_front_matter(md_text)
    body = re.sub(
        r"(?s)<!-- AUTOGENERATED:CITE-LIST START -->.*?<!-- AUTOGENERATED:CITE-LIST END -->",
        "",
        body,
    )
    lines = body.splitlines()
    section = "Artículos"
    keys = []
    seen = set()
    section_keys = {}
    key_section = {}

    heading_re = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*$")
    cite_re = re.compile(r"(?<!\w)@([A-Za-z0-9:_\-.]+)")

    for line in lines:
        hm = heading_re.match(line)
        if hm:
            section = hm.group(1).strip()
            section_keys.setdefault(section, [])
            continue

        for m in cite_re.finditer(line):
            key = m.group(1)
            if key not in seen:
                seen.add(key)
                keys.append(key)
                section_keys.setdefault(section, [])
                section_keys[section].append(key)
                key_section[key] = section

        for m in re.finditer(r'\{\{<\s*cite\s+key="([^"]+)"\s*>\}\}', line):
            key = m.group(1).strip()
            if not key:
                continue
            if key not in seen:
                seen.add(key)
                keys.append(key)
                section_keys.setdefault(section, [])
                section_keys[section].append(key)
                key_section[key] = section

    return keys, section_keys, key_section


def build_author(item):
    authors = item.get("author", [])
    names = []
    for a in authors:
        given = str(a.get("given", "")).strip()
        family = str(a.get("family", "")).strip()
        if given and family:
            names.append(f"{given} {family}")
        elif family:
            names.append(family)
        elif given:
            names.append(given)
    return ", ".join(names)


def build_citation(item):
    if item.get("citation"):
        return str(item["citation"])

    title = str(item.get("title", "")).strip()
    container = str(item.get("container-title", "")).strip()
    volume = str(item.get("volume", "")).strip()
    issue = str(item.get("issue", "")).strip()
    year = ""
    issued = item.get("issued", {})
    if isinstance(issued, dict):
        dps = issued.get("date-parts", [])
        if dps and dps[0]:
            year = str(dps[0][0])

    parts = []
    if title:
        parts.append(f"<em>{title}</em>")
    if container:
        parts.append(container)
    if volume:
        parts.append(f"Vol. {volume}")
    if issue:
        parts.append(f"No. {issue}")

    out = ", ".join(parts)
    if year:
        out += f" ({year})"
    return out


def key_to_slug(key: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9._-]+", "-", key).strip("-").lower()
    return slug or "item"


def title_to_slug(text: str) -> str:
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "item"


def extract_front_matter_date(md_text: str) -> str:
    m = re.search(r"(?s)\A---\n(.*?)\n---\n?", md_text)
    if not m:
        return ""
    front_matter = m.group(1)
    dm = re.search(r"(?m)^date:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})\s*$", front_matter)
    return dm.group(1) if dm else ""


def generate_item_page(item, key, out_path: Path, forced_type: str):
    title = str(item.get("title", "")).strip()
    author = build_author(item)
    status = str(item.get("status", "published")).strip() or "published"
    item_type = forced_type or str(item.get("type_content", "articulos")).strip() or "articulos"
    citation = build_citation(item)
    tags = item.get("tag", ["governance"])
    if not isinstance(tags, list) or not tags:
        tags = ["governance"]
    subjects = str(item.get("subjects", "law")).strip() or "law"
    comments = str(item.get("comments", "no")).strip() or "no"
    fm_date = str(item.get("date", "")).strip() or ymd_from_obj(item.get("issued", {})) or date.today().isoformat()
    delivery_date = str(item.get("delivery_date", "")).strip() or ymd_from_obj(item.get("submitted", {}))
    acceptance_date = str(item.get("acceptance_date", "")).strip() or ymd_from_obj(item.get("accepted", {}))
    doi = str(item.get("DOI", item.get("doi", ""))).strip()
    uri = str(item.get("uri", item.get("URL", ""))).strip()
    issn = str(item.get("ISSN", item.get("issn", ""))).strip()
    isbn = str(item.get("ISBN", item.get("isbn", ""))).strip()
    pages = str(item.get("page", item.get("pages", ""))).strip()
    abstract = str(item.get("abstract", "")).strip()

    tag_yaml = ", ".join([yaml_quote(str(t)) for t in tags])

    frontmatter = [
        "---",
        f"title: {yaml_quote(title)}",
        f"author: {author}",
        f"status: {status}",
        f"type: {item_type}",
        f"citation: {yaml_quote(citation)}",
        f"tag: [{tag_yaml}]",
        f"subjects: {subjects}",
        f"comments: {comments}",
        f"date: {fm_date}",
        f"delivery_date: {delivery_date}",
        f"acceptance_date: {acceptance_date}",
        f"doi: {doi}",
    ]
    if uri:
        frontmatter.append(f"uri: {uri}")
    if issn:
        frontmatter.append(f"issn: {issn}")
    if isbn:
        frontmatter.append(f"isbn: {isbn}")
    if pages:
        frontmatter.append(f"pages: {pages}")
    frontmatter.extend(
        [
            "filter:",
            "  - erb",
            "  - markdown",
            "  - rubypants",
            "---",
            "",
        ]
    )

    content = frontmatter + [""]
    if abstract:
        content.extend(
            [
                "## Abstract",
                "",
                abstract,
                "",
            ]
        )
    else:
        content.extend(
            [
                "## Abstract",
                "",
                "_No abstract available in references.json._",
                "",
            ]
        )

    out_path.write_text("\n".join(content), encoding="utf-8")


def rewrite_index_with_list(index_path: Path, section_keys, refs_by_id, slug_by_key):
    text = index_path.read_text(encoding="utf-8")
    lines = ["", "<!-- AUTOGENERATED:CITE-LIST START -->", "", "## Citekey List", ""]
    for section, keys in section_keys.items():
        if not keys:
            continue
        lines.append(f"### {section}")
        lines.append("")
        for key in keys:
            item = refs_by_id.get(key, {})
            slug = slug_by_key[key]
            title = str(item.get("title", key)).strip() or key
            lines.append(f"- `@{key}`: {{{{< cite key=\"{key}\" >}}}} ([{title}](./{slug}/))")
        lines.append("")

    lines.extend(["", "<!-- AUTOGENERATED:CITE-LIST END -->", ""])
    block = "\n".join(lines)

    pattern = re.compile(
        r"\n<!-- AUTOGENERATED:CITE-LIST START -->.*?<!-- AUTOGENERATED:CITE-LIST END -->\n?",
        re.S,
    )
    if pattern.search(text):
        updated = pattern.sub("\n" + block, text)
    else:
        updated = text.rstrip() + "\n" + block
    index_path.write_text(updated, encoding="utf-8")


def main():
    args = parse_args()
    index_path = Path(args.index_file).resolve()
    output_dir = Path(args.output_dir).resolve()
    refs_path = Path(args.references).resolve()

    if not index_path.exists():
        raise SystemExit(f"_index.md not found: {index_path}")
    if not refs_path.exists():
        raise SystemExit(f"references file not found: {refs_path}")

    index_text = index_path.read_text(encoding="utf-8")
    keys, section_keys, key_section = extract_citekeys_by_section(index_text)
    if not keys:
        raise SystemExit(f"No citekeys found in: {index_path}")

    refs = json.loads(refs_path.read_text(encoding="utf-8"))
    refs_by_id = {str(item.get("id", "")): item for item in refs}

    missing = [k for k in keys if k not in refs_by_id]
    if missing:
        raise SystemExit(f"Citekeys missing in references: {', '.join(missing)}")

    output_dir.mkdir(parents=True, exist_ok=True)
    used = set()
    slug_by_key = {}
    for key in keys:
        item = refs_by_id[key]
        base_slug = title_to_slug(str(item.get("title-short") or item.get("title") or key))
        slug = base_slug
        if slug in used:
            slug = f"{base_slug}-{key_to_slug(key)}"
        used.add(slug)
        slug_by_key[key] = slug
        item_path = output_dir / f"{slug}.md"
        forced_type = heading_to_type(key_section.get(key, "Artículos"))
        generate_item_page(refs_by_id[key], key, item_path, forced_type)

    rewrite_index_with_list(index_path, section_keys, refs_by_id, slug_by_key)
    print(f"Updated index list: {index_path}")
    print(f"Wrote item files in: {output_dir}")


if __name__ == "__main__":
    main()
